/*
 * Yagna Activity API
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package network.golem.yajapi.activity.apis;

import network.golem.yajapi.activity.ApiException;
import network.golem.yajapi.activity.models.ActivityState;
import network.golem.yajapi.activity.models.ErrorMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProviderApi
 */
@Ignore
public class ProviderApiTest {

    private final ProviderApi api = new ProviderApi();

    /**
     * Fetch Requestor command events.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void collectActivityEventsTest() throws ApiException {
        Float timeout = null;
        Integer maxEvents = null;
        List<Object> response = api.collectActivityEvents(timeout, maxEvents);

        // TODO: test validations
    }
    /**
     * Get state of specified Activity.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityStateTest() throws ApiException {
        String activityId = null;
        ActivityState response = api.getActivityState(activityId);

        // TODO: test validations
    }
    /**
     * Get usage of specified Activity.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityUsageTest() throws ApiException {
        String activityId = null;
        List<Double> response = api.getActivityUsage(activityId);

        // TODO: test validations
    }
    /**
     * Lists all Activity ids for Provider identified by app_key.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listActivitiesTest() throws ApiException {
        List<String> response = api.listActivities();

        // TODO: test validations
    }
    /**
     * Set state of specified Activity.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setActivityStateTest() throws ApiException {
        ActivityState body = null;
        String activityId = null;
        api.setActivityState(body, activityId);

        // TODO: test validations
    }
}
