/*
 * Yagna Activity API
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package network.golem.yajapi.activity.apis;

import network.golem.yajapi.activity.ApiException;
import java.math.BigDecimal;
import network.golem.yajapi.activity.models.ErrorMessage;
import network.golem.yajapi.activity.models.ExeScriptCommandResult;
import network.golem.yajapi.activity.models.ExeScriptRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequestorControlApi
 */
@Ignore
public class RequestorControlApiTest {

    private final RequestorControlApi api = new RequestorControlApi();

    /**
     * Creates new Activity based on given Agreement.
     *
     * **Note:** This call shall get routed as a provider event (see ProviderEvent structure).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActivityTest() throws ApiException {
        String body = null;
        String response = api.createActivity(body);

        // TODO: test validations
    }
    /**
     * Destroys given Activity.
     *
     * **Note:** This call shall get routed as a provider event (see ProviderEvent structure).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void destroyActivityTest() throws ApiException {
        String activityId = null;
        api.destroyActivity(activityId);

        // TODO: test validations
    }
    /**
     * Executes an ExeScript batch within a given Activity.
     *
     * **Note:** This call shall get routed directly to ExeUnit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void execTest() throws ApiException {
        ExeScriptRequest body = null;
        String activityId = null;
        String response = api.exec(body, activityId);

        // TODO: test validations
    }
    /**
     * Queries for ExeScript batch results.
     *
     * **Note:** This call shall collect ExeScriptCommand result objects received directly from ExeUnit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExecBatchResultsTest() throws ApiException {
        String activityId = null;
        String batchId = null;
        BigDecimal commandIndex = null;
        Float timeout = null;
        List<ExeScriptCommandResult> response = api.getExecBatchResults(activityId, batchId, commandIndex, timeout);

        // TODO: test validations
    }
}
