/*
 * Yagna Activity API
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package network.golem.yajapi.activity.apis;

import network.golem.yajapi.activity.ApiException;
import network.golem.yajapi.activity.models.ActivityState;
import network.golem.yajapi.activity.models.ErrorMessage;
import network.golem.yajapi.activity.models.ExeScriptCommandState;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequestorStateApi
 */
@Ignore
public class RequestorStateApiTest {

    private final RequestorStateApi api = new RequestorStateApi();

    /**
     * Get state of specified Activity.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityStateTest() throws ApiException {
        String activityId = null;
        ActivityState response = api.getActivityState(activityId);

        // TODO: test validations
    }
    /**
     * Get usage of specified Activity.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityUsageTest() throws ApiException {
        String activityId = null;
        List<Double> response = api.getActivityUsage(activityId);

        // TODO: test validations
    }
    /**
     * Get running command for a specified Activity.
     *
     * **Note:** This call shall get routed directly to ExeUnit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRunningCommandTest() throws ApiException {
        String activityId = null;
        ExeScriptCommandState response = api.getRunningCommand(activityId);

        // TODO: test validations
    }
}
