/*
 * Yagna Activity API
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package network.golem.yajapi.activity.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * ActivityUsage
 */


public class ActivityUsage implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("currentUsage")
  private List<Double> currentUsage = null;

  @JsonProperty("timestamp")
  private Integer timestamp = null;

  public ActivityUsage currentUsage(List<Double> currentUsage) {
    this.currentUsage = currentUsage;
    return this;
  }

  public ActivityUsage addCurrentUsageItem(Double currentUsageItem) {
    if (this.currentUsage == null) {
      this.currentUsage = new ArrayList<>();
    }
    this.currentUsage.add(currentUsageItem);
    return this;
  }

   /**
   * Current usage vector
   * @return currentUsage
  **/
  @Schema(description = "Current usage vector")
  public List<Double> getCurrentUsage() {
    return currentUsage;
  }

  public void setCurrentUsage(List<Double> currentUsage) {
    this.currentUsage = currentUsage;
  }

  public ActivityUsage timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Usage update timestamp (UTC)
   * @return timestamp
  **/
  @Schema(description = "Usage update timestamp (UTC)")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityUsage activityUsage = (ActivityUsage) o;
    return Objects.equals(this.currentUsage, activityUsage.currentUsage) &&
        Objects.equals(this.timestamp, activityUsage.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentUsage, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityUsage {\n");
    
    sb.append("    currentUsage: ").append(toIndentedString(currentUsage)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
